# Generated by Django 5.2.7 on 2025-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
